{% set name = "treelib" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2b57ba38290f7da6af97b41de8ff7be98e7a8c00815f95d0782241f77503952

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - six
    - python

{% set tests_to_skip = "" %}
# UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-9: character maps to <undefined>
{% set tests_to_skip = "not test_show" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - treelib
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - export PYTHONIOENCODING=UTF-8
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/caesar0301/treelib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Tree implementation in python. Simple for you to use.
  description: |
    Tree is an important data structure in computer science.
    Examples are shown in ML algorithm designs such as random forest
    tree and software engineering such as file system index. treelib is
    created to provide an efficient implementation of tree data structure in Python.
  doc_url: https://treelib.readthedocs.io
  dev_url: https://github.com/caesar0301/treelib

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - maxhora
