travis:
  secure:
    BINSTAR_TOKEN: Gyqi4oZFtLK2lDjxwCu0E7v+q4ZXqVsa+wfyVEU3yxywSkVaFr0TkqEfxfk4N49RJBS8gokrLTdpyegwhA/Du38vkne2mhcaEQuJPhjtUM9dt7RfBBTM29M2rWEYz8RoHsRo1hAhXTYyBsEmCQAQxrbXs0CAYLjTHyVdW7GFdp/J+doec9PBTrMwDAyutJJRnqT+AgETpUNbFSzG5jBLyi6G7SY1VgiemsoU7KEVzjiGrQL6a5bf2Gu3bDO/atopwH9f6DOYgWkKPTmGTaADdJzURMq5wAu0gIPULHhbR95/8BVCOw7lBiZcKV2JFpKjDfoFlcqfysIm6DWWuzKA/XF2kVUSiK/QMBD3YkynE8W0LYb+2ZrNSsijP2TEHN0iy4vEECA07AcGUf6oGi7+0WTKudZxOtJuAMUal7hoQ5rUogu1l9nKbB1j6OU37CNaXKhu/c77RFM/xUYej1FebgAp2y33eLwdqOZl5sqeNbSBik9B/HQE6Z0XbKWsk8ZhBwY52RQBi1pitHORamt/RT65IjGwDxK9+3BTHaVf5DPUkMuIyeIsLv6Xy8cKbC+v1y+zhkL+MpnwDprt97kDoFAR/7U9z+P6f5Uci/B5fws5bDwBJLV2mpcLaIaak9Oz4IkzoKvrCDhR9/rzPYUGyhQUli/bxhqqk0GxHgWTuoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
